Chore: new package structure with src  dir, vitest, deps updates, revamped actions and more
storyblok/storyblok-astro pull request #1016
Opened 2024-12-05 06:36 UTC by dipankarmaikap

This PR introduces a new structure and multiple improvements, including:

- Moved to `src` directory instead of `lib`.
- Refactored project under `pnpm` workspaces.
- Cypress config and folder moved to root.
- Default E2E runs against `playground/test` (more coverage needed).
- Added Vitest function tests (more tests needed).
- Updated GitHub Actions with `commitlint` and separate workflows for lint/test.
- Upgraded dependencies (no breaking changes to SDK).

2024-12-09 11:35 UTC, manuelschroederdev approved these changes

2024-12-09 11:45 UTC, alvarosabu requested changes
Doing the QG

2024-12-09 13:59 UTC, alvarosabu requested changes
Hi @dipankarmaikap amazing job you did here. Just one minor blocking point, I also added some commit suggestion to ease the changes required. Let me know if you have any questions or something you need support with

2024-12-12 07:51 UTC, dipankarmaikap commented on playground/ssg/astro.config.mjs
> +    plugins: [mkcert()],
If we do this we get the following error
```js
Unknown file extension ".astro" for ..../dist/components/StoryblokComponent.astro
You likely need to add this package to `vite.ssr.noExternal` in your astro config file.
```

2024-12-12 10:41 UTC, manuelschroederdev commented on playground/ssg/astro.config.mjs
> +      accessToken: 'OsvNv534kS2nivAAj1EPVgtt',
Hey @alvarosabu, I'd suggest we keep it as it is for this PR and tackle replacing the tokens with env variables in a subsequent step for all frameworks? :-)

2024-12-12 10:42 UTC, alvarosabu approved these changes

2024-12-12 12:45 UTC, merged