feat!: making livepreview stable and removing `useStoryblok` function
storyblok/storyblok-astro pull request #1050
Opened 2024-12-30 10:56 UTC by dipankarmaikap

This PR stabilizes the experimental Live Preview feature and introduces breaking changes. The `useStoryblok` hook is now deprecated and replaced by the new `getLiveStory` function. Below are the key updates and usage examples.

### **Breaking Changes**
1. **Removal of `useStoryblok`:**  
   The `useStoryblok` hook has been deprecated in favor of `getLiveStory`. This function simplifies the implementation of live preview in your Astro application.

2. **Named Export for `storyblok`:**  
   The `storyblok` initialization is now exported as a named export instead of a default export. Update your `astro.config.mjs` imports accordingly.

---

### **Usage Example**
Configure Storyblok in `astro.config.mjs` using the named export:  
```js
import { storyblok } from '@storyblok/astro';

export default {
  integrations: [
    storyblok({
      accessToken: 'OsvN....',
      bridge: {
        resolveRelations: ['featured-articles.posts'],
      },
      enableFallbackComponent: true,
      livePreview: true,
    }),
  ],
};
```

#### **Page Example**
Here’s how you can use `getLiveStory` in a page:  
```astro
---
// pages/[...slug].astro
import {
  getLiveStory,
  useStoryblokApi,
  type ISbStoryData,
} from '@storyblok/astro';
import StoryblokComponent from '@storyblok/astro/StoryblokComponent.astro';
import BaseLayout from '../layouts/Layout.astro';

const { slug } = Astro.params;
let story: ISbStoryData | null = null;

const liveStory = await getLiveStory(Astro);
if (liveStory) {
  story = liveStory;
} else {
  const sbApi = useStoryblokApi();
  const { data } = await sbApi.get(`cdn/stories/${slug || 'home'}`, {
    version: 'draft',
    resolve_relations: ['featured-articles.posts'],
  });
  story = data?.story;
}
---

<BaseLayout>
  {story && <StoryblokComponent blok={story.content} />}
</BaseLayout>
```

#### **Listening for Live Preview Updates**
When the live preview updates content in the Storyblok editor, a custom event (`storyblok-live-preview-updated`) is triggered. Applications can listen for this event as follows:  
```js
<script>
  document.addEventListener("storyblok-live-preview-updated", () => {
    console.log("Live preview: body updated");
  });
</script>
```

### **Closing Issues**
This PR addresses and closes the following issue(s):  
- Closes #864  
- Closes #943
- Closes #907
- Closes #895

2024-12-30 12:04 UTC, alexjoverm requested changes
Hey @dipankarmaikap this is a great PR, thanks! The named export is ideal for bundling as is set as a standard, and I like how the `getLiveStory` it's particularly adapted for Astro's api needs.

I added you a comment about a typo.

Also, can we add some tests on the new feature/changes? I know some parts of this SDK might not be too easy to test, mostly due to Astro integration. However, as a general developing practice, we should always ensure that what we publish is decently tested, at least with some minimal tests.

2024-12-31 09:23 UTC, JakiChen commented
heyyyy, @dipankarmaikap, @alexjoverm  I'm not sure if that's more straightforward：It is to directly allow users to access `liveStory` through `locals`

- Or it can solve the problem that Astro needs to be manually configured directly as a context.

- Or simply provide a `LiveStorkyblokComponents`?

Finally, thanks to the team's efforts and improvements, this is the most user-friendly headless CMS I've experienced so far

```astro
---
// pages/[...slug].astro
import {
  getLiveStory,
  useStoryblokApi,
  type ISbStoryData,
} from '@storyblok/astro';
import StoryblokComponent from '@storyblok/astro/StoryblokComponent.astro';
import BaseLayout from '../layouts/Layout.astro';

const { slug } = Astro.params;
let story: ISbStoryData | null = null;

if (Astro.locals.liveStory) {
  story = liveStory;
} else {
  const sbApi = useStoryblokApi();
  const { data } = await sbApi.get(`cdn/stories/${slug || 'home'}`, {
    version: 'draft',
    resolve_relations: ['featured-articles.posts'],
  });
  story = data?.story;
}
---

<BaseLayout>
  {story && <StoryblokComponent blok={story.content} />}
</BaseLayout>
```

2025-01-14 14:18 UTC, dipankarmaikap commented
Hey @JakiChen 
As an end user, you already have access to the `locals` object—nothing prevents you from utilizing it directly. However, we believe our `getLiveStory` helper function provides a convenient solution for most users who prefer not to implement their own.
```js
export async function getLiveStory(Astro: AstroGlobal) {
  let story: ISbStoryData | null = null;
  if (Astro && Astro.locals._storyblok_preview_data) {
    story = Astro.locals._storyblok_preview_data;
  }
  return story;
}
```
Regarding your suggestion about `LiveStoryblokComponents`, adding such functionality would introduce additional overhead to the SDK. We aim to keep the SDK lightweight and efficient, and the current approach with `getLiveStory` offers a minimal yet effective abstraction.

Let me know if you have further thoughts or questions!

2025-01-15 10:44 UTC, JakiChen commented
heyyyyy, @dipankarmaikap 

I'm not sure if the current getLiveStory() function supports `i18n` content. （From the logic of middleware, it should be supported. After all, `locals.liveStory` (current called `locals._storyblok_preview_data`) is only related to the data POSTed by the current page.）

My opinion is not very important, I just prefer a simpler, scalable and elegant way (like the `storyblok-js-client` system): No code like `{story && <StoryblokComponent blok={story.content} />}` or something like that.

2025-01-15 10:50 UTC, dipankarmaikap commented
`{story && <StoryblokComponent blok={story.content} />}` is not a strict requirement. You can simply use `<StoryblokComponent blok={story.content} />` as you’ve done. The example was set up with TypeScript in strict mode, and my configuration enforces handling potential `null` values.

2025-01-17 08:59 UTC, dipankarmaikap commented
Closing this for #1061

2025-01-17 08:59 UTC, closed without merging