Add Option to Specify Components Root Directory
storyblok/storyblok-astro pull request #107
Opened 2023-02-20 03:51 UTC by rayhanadev

I mentioned this in `#storyblok` on the Astro Discord server. Still, it would be nice to specify an alternative to the expected `/src/` directory since it can be configured and changed in the `astro.config.mjs` file.

An example would be where my project opts for `/app/` instead of `/src/` since I am running a mono repo and having a directory named `/src/` would not make too much sense.

This pull request makes two changes, it introduces a configuration option called `componentsDir` which is a string that can be set to an alternative to `/src/` (default: `/src/`). This was documented with JSDoc. :)

I also modified the `vite-plugin-storyblok-components` function to have a root parameter that will switch out the `/src/` string on line 21 with root.

E2E tests ran with success :+1:, and my changes were minor so I could follow your style guide.

2023-02-20 13:39 UTC, manuelschroederdev approved these changes

2023-02-20 17:13 UTC, rayhanadev reviewed
:+1:

2023-02-21 08:06 UTC, edv-ns commented
Besides inconsistent indentation and probably README update missing, looks nice 💪

2023-02-21 14:58 UTC, alexjoverm requested changes
Thanks for this @rayhanadev! As we're adding a new option, we'll need also the docs and tests parts covered as well.

Can you add this new option to the Readme? Also, let us know if you need any support for writting a simple test for this ;)

2023-02-21 16:54 UTC, rayhanadev commented
> Besides inconsistent indentation and probably README update missing, looks nice 💪

ohhh thats my bad oops 😅

> Can you add this new option to the Readme? Also, let us know if you need any support for writting a simple test for this ;)

sure thing! :D

2023-02-23 14:59 UTC, rayhanadev commented
Added documentation :tada: @alexjoverm how should I go about adding tests? :) Should I modify the `playground-test`?

2023-02-23 16:55 UTC, manuelschroederdev commented
Hey @rayhanadev thank you! 🙂
Yes, feel free to modify `playground-test` and `lib/cypress` accordingly. Let us know if you require any assistance.

2023-02-23 20:41 UTC, rayhanadev commented
I think its good! :D

2023-03-10 17:03 UTC, alexjoverm requested changes
Impressive work @rayhanadev! Thanks also for the extra additions you did on the test playground. Only a couple of very minor things from my side, but other than that we're ready to go 🚀

2023-03-10 17:03 UTC, alexjoverm commented on playground-test/astro.config.mjs
> +  srcDir: path.join(__dirname, './app'),
Is the indentation fine here?

2023-03-11 03:42 UTC, closed without merging

2023-03-29 07:06 UTC, manuelschroederdev commented
Hey @rayhanadev can you open the PR again? 🙂

2023-03-29 16:05 UTC, edv-ns commented
Hey @rayhanadev I would really need your change for my project 🙏 Let's please merge it!