Update dependencies
storyblok/storyblok-astro pull request #956
Opened 2024-10-29 10:36 UTC by manuelschroederdev

2024-10-30 10:13 UTC, alvarosabu requested changes
@manuelschroederdev I would just update minors and patches since majors have some breaking changes

2024-10-30 10:13 UTC, alvarosabu commented on package.json
> +    "eslint": "^9.13.0",
@manuelschroederdev we shouldn't update to v9 of eslint until we get the new pnpm setup with eslint flat config and `@storyblok/eslint-config` package

2024-10-30 10:13 UTC, alvarosabu commented on package.json
> +    "@typescript-eslint/parser": "^8.12.1",
Probably would avoid updating this major as well for now

2024-10-30 16:52 UTC, manuelschroederdev commented
Hey @alvarosabu, thanks for checking, I've made the changes.

2024-10-31 11:46 UTC, alvarosabu approved these changes
Thanks @manuelschroederdev

2024-10-31 11:46 UTC, merged